services:
    database:
        build:
            context: .
            dockerfile: ./Docker/db.Dockerfile
        container_name: database
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: prog_demos
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - backend-network
        ports:
            - '5432:5432'
        healthcheck:
            test: 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
            interval: 2s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: ./Docker/app.Dockerfile
        container_name: backend
        depends_on:
            database:
                condition: service_healthy
        environment:
            DB_HOST: database
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: prog_demos
            PORT: 8080
            TASK-RUNNER-URL: http://task-runner:3000/execute
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - solutions:/var/temp_solutions/
        ports:
            - '8080:8080'
        networks:
            - backend-network

    task-runner:
        build:
            context: .
            dockerfile: ./Docker/task-runner.Dockerfile
        container_name: task-runner
        mem_limit: 1024m
        cpu_count: 2
        environment:
            PORT: 3000
        volumes:
            - solutions:/var/temp_solutions/
        expose:
            - 3000
        networks:
            - backend-network

volumes:
    db_data:
    solutions:

networks:
    backend-network:
        driver: bridge
