services:
    database:
        build:
            context: .
            dockerfile: ./Docker/db.Dockerfile
        container_name: database
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: prog_demos
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - backend-network
        healthcheck:
            test: 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
            interval: 2s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: ./Docker/app.Dockerfile
        container_name: backend
        depends_on:
            database:
                condition: service_healthy
        environment:
            DB_HOST: database
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: prog_demos
            PORT: 8080
            TASKS_VOLUME_NAME: prog-demos-backend_tasks
            PROD: 1
            USE_LOKI: 1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - tasks:/var/temp_tasks/
        ports:
            - '127.0.0.1:8080:8080'
        networks:
            - backend-network

volumes:
    db_data:
    tasks:

networks:
    backend-network:
        driver: bridge
